//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hapgo.Domain.Models
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Delivery : IObjectState
    {
        public System.Guid ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? LastLogin { get; set; }
        public string Description { get; set; }
        public string IP { get; set; }
        public DateTime? Birthday { get; set; }
        public string Gender { get; set; }
        public Guid? CountryID { get; set; }
        public string Email { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string ZipCode { get; set; }
        public Guid? CurrencyID { get; set; }
        public Guid? QuestionID { get; set; }
        public string Answer { get; set; }
        public string Address { get; set; }
        public byte? Status { get; set; }
        public double? CommSetting { get; set; }
        public string Club { get; set; }
        public DateTime? LastModified { get; set; }
        public double? Balance { get; set; }
        public double? Credit { get; set; }
        public string ActiveID { get; set; }
        public Guid? Question { get; set; }
        public string QuestionName { get; set; }
        public string MarketingID { get; set; }
        public DateTime? PasswordExpiry { get; set; }

        [NotMapped]
        public ObjectState ObjectState { get; set; }
    }
}
